### ISSUE TITLE
when run mate-recorder command, the program dialog will not show until a long time

### ISSUE THREAD

**Issue by prownd** [zhuyaliang/mate-recorder#2]
i git clone the code , then compile it . but when i run command  mate-recorder , the dialog will not show until  some second gone.

**Comment by prownd** [comment]
I got it . it is blocked by notification dbus timeout.  and i sloved the problem.  
It is my  environment issue.   i installed the mate  and kde in my pc.  so the notificaion bus name of mate and kde is same. 
It work well when remove the kde notification bus conf .

**Comment by zhuyaliang** [comment]
@prownd Very good. Congratulations on solving this problem.Let's close this issue
