### ISSUE TITLE
recorder when selection window . it still recorder area

### ISSUE THREAD

**Issue by prownd** [zhuyaliang/mate-recorder#3]
1: select area , recorder screen.  work well.
2: then select window . but  it is still  recorderd area

**Comment by zhuyaliang** [comment]
Thank you for your testing and suggestions. I will solve this problem as soon as possible

**Comment by zhuyaliang** [comment]
@prownd  This problem has been fixed in the newly submitted code.If you have enough time, please confirm whether this problem is really solved。

**Comment by prownd** [comment]
Yeah.  it is fixed.   work well.
